import contextlib

from .common_types import ContextType
from .exception_handlers import (
    handle_explicit_pydantic_error,
    http_exception_handler,
    pydantic_validation_error_exception_handler,
    validation_error_exception_handler,
)
from .exceptions import (
    NotFoundException,
    PermissionActionException,
    PermissionException,
    UnauthorizedException,
)
from .interactors import (
    AnyApiDataInteractor,
    ApiDataInteractor,
    ApiDataInteractorT,
    BaseHooksMixin,
    M2MCreateUpdateConfig,
)
from .permissions import (
    BasePermission,
    PermissionInstanceT,
    RequestData,
    UserT,
    get_permissions_dependency,
)
from .repositories import (
    AnnotationT,
    AnyApiRepositoryProtocol,
    APIModel,
    APIModelT,
    ApiRepositoryProtocol,
    ApiRepositoryProtocolT,
    LazyLoadedT,
    OrderingClauseT,
    SelectStatementT,
    WhereFilterT,
)
from .validators import (
    AnyGenericInput,
    AnyGenericOutput,
    ApiDataType,
    BaseListValidator,
    BaseModelListValidator,
    BaseModelValidator,
    BaseValidator,
    DatetimeValidator,
    GenericError,
    LOCType,
    NotEqualToValues,
    ObjectPKValidator,
    RegexValidator,
    TimeZoneValidator,
    UniqueByFieldValidator,
    UniqueConstraintType,
    ValidationError,
    ValidationErrorSchema,
    ValidationErrorType,
    ValidationMapType,
)
from .views import (
    DEFAULT_ERROR_RESPONSES,
    ActionMixin,
    ActionResponsesMap,
    AnyBaseAPIView,
    AnyFilters,
    BaseAPIView,
    BaseAPIViewMeta,
    BaseAPIViewMixin,
    Context,
    CreateMixin,
    CreateSchema,
    DeleteMixin,
    DetailMixin,
    DetailSchema,
    Filters,
    FiltersT,
    ListMixin,
    ListSchema,
    PaginatedBaseModel,
    PaginatedResult,
    PaginationParams,
    ResponsesMap,
    UpdateMixin,
    UpdateSchema,
    action,
)

with contextlib.suppress(ImportError):
    from . import sqlalchemy

with contextlib.suppress(ImportError):
    from . import testing

with contextlib.suppress(ImportError):
    from . import jwt

with contextlib.suppress(ImportError):
    from . import s3


__all__ = (
    "sqlalchemy",
    "jwt",
    "testing",
    "s3",
    "action",
    "ActionMixin",
    "ActionResponsesMap",
    "AnnotationT",
    "AnyApiDataInteractor",
    "AnyApiRepositoryProtocol",
    "AnyBaseAPIView",
    "AnyFilters",
    "AnyGenericInput",
    "AnyGenericOutput",
    "ApiDataInteractor",
    "ApiDataInteractorT",
    "ApiDataType",
    "APIModel",
    "APIModelT",
    "ApiRepositoryProtocol",
    "ApiRepositoryProtocolT",
    "BaseAPIView",
    "BaseAPIViewMeta",
    "BaseAPIViewMixin",
    "BaseHooksMixin",
    "BaseListValidator",
    "BaseModelListValidator",
    "BaseModelValidator",
    "BasePermission",
    "BaseValidator",
    "Context",
    "ContextType",
    "CreateMixin",
    "CreateSchema",
    "DatetimeValidator",
    "DEFAULT_ERROR_RESPONSES",
    "DeleteMixin",
    "DetailMixin",
    "DetailSchema",
    "Filters",
    "FiltersT",
    "GenericError",
    "get_permissions_dependency",
    "handle_explicit_pydantic_error",
    "http_exception_handler",
    "LazyLoadedT",
    "ListMixin",
    "ListSchema",
    "LOCType",
    "M2MCreateUpdateConfig",
    "NotEqualToValues",
    "NotFoundException",
    "ObjectPKValidator",
    "OrderingClauseT",
    "PaginatedBaseModel",
    "PaginatedResult",
    "PaginationParams",
    "PermissionActionException",
    "PermissionException",
    "PermissionInstanceT",
    "pydantic_validation_error_exception_handler",
    "RegexValidator",
    "RequestData",
    "ResponsesMap",
    "SelectStatementT",
    "TimeZoneValidator",
    "UnauthorizedException",
    "UniqueByFieldValidator",
    "UniqueConstraintType",
    "UpdateMixin",
    "UpdateSchema",
    "UserT",
    "validation_error_exception_handler",
    "ValidationError",
    "ValidationErrorSchema",
    "ValidationErrorType",
    "ValidationMapType",
    "WhereFilterT",
)
